### ISSUE TITLE
Bugged reaction and edit buttons

### ISSUE THREAD

**Issue by ReptilianD** [tehbasshunter/theme-fixes#1]
https://puu.sh/w0HNI/16a5ad185a.mp4

The problem can be seen in the video provided, everything works fine in the default skin, i tried re-installing and refreshing discord a couple of times.

**Comment by Queen-Liz** [comment]
@ReptilianD Just right click instead

**Comment by tehbasshunter** [comment]
Supposedly there is something that can fix it. I just need to add it along with the other CSS updates. Give me until I get home in the morning and get you a copy to test.

**Comment by ReptilianD** [comment]
ok thank you

2017-07-31 8:14 GMT+02:00 Chris <notifications@github.com>:

**Comment by tehbasshunter** [comment]
Since GH only lets me upload certain filetypes I had to change this to "work". Simply change the extension back to CSS and it **_SHOULD_** work with that.  
  
Let me know if this doesn't work.  

[Nova Test Fix](https://github.com/tehbasshunter/theme-fixes/files/1188307/Nova.Test.Fixes.theme.txt)

**Comment by ReptilianD** [comment]
I can't download it, it sends me to a 404 error page

2017-07-31 19:20 GMT+02:00 Chris <notifications@github.com>:

**Comment by tehbasshunter** [comment]
[I blame the issues that GH is/was having right now. This WILL work though......](https://gist.github.com/tehbasshunter/84780475a12986b500ac8f21a2f7fd36)

**Comment by tehbasshunter** [comment]
I won't be able to respond after this as I'll be asleep cause work tonight.

**Comment by ReptilianD** [comment]
It didn't work, perhaps it's something on my end but other themes seem to
work

2017-07-31 20:03 GMT+02:00 Chris <notifications@github.com>:

**Comment by Modder4869** [comment]
```css
.markup {
    backface-visibility: unset;
}

```
this fixes it ⌛️

**Comment by tehbasshunter** [comment]
This actually fixed it. Have made the changes and removed the "fix" I had in place.
