### ISSUE TITLE
A nice discord theme that has issues for you to fix please :)

### ISSUE THREAD

**Issue by FindingSum3662** [tehbasshunter/theme-fixes#2]
https://betterdocs.net/themes/battlefield.html

people complain that the city is not appearing like its suppose to and it does the same for me :) please fix this issue the picture it's supposed to be displaying and also suppose to look like  is http://i.imgur.com/7CIXUsu.png)

**Comment by tehbasshunter** [comment]
As this is not a theme submitted on the betterdiscord server I will not be adding it.  
  
As they also stated that they won't be maintaining it any more you're on your own.
