### ISSUE TITLE
Message menu broken in Nova theme

### ISSUE THREAD

**Issue by FFY00** [tehbasshunter/theme-fixes#5]
![deepin-screen-recorder_select area_20180512181612](https://user-images.githubusercontent.com/11718923/39959911-ec3663e2-5610-11e8-82b8-231124347dc1.gif)
![deepin-screen-recorder_select area_20180512181652](https://user-images.githubusercontent.com/11718923/39959912-ec609cca-5610-11e8-8b8d-4856597fdba2.gif)

**Comment by tehbasshunter** [comment]
Yeah....about that.  
  
Totally didn't forget to add the fix for this when I redid it >.<  
  
Add this to customCSS or the bottom of the theme file.
`.markup {
    backface-visibility: unset;
}`
